export const RoomReserved = [
  {
    serialNo: 1,
    roomName: 'Sport Room',
    availability: '✅',
    description: 'For basketball practice',
    reservedDate: '2024-03-10',
    reservedHours: 2,
  },
  {
    serialNo: 2,
    roomName: 'Auditorium A',
    availability: '🔴',
    description: 'Seminar on Robotics',
    reservedDate: '2024-03-12',
    reservedHours: 4,
  },
  {
    serialNo: 3,
    roomName: 'Classroom 101',
    availability: '✅',
    description: 'English Literature Lecture',
    reservedDate: '2024-03-11',
    reservedHours: 3,
  },
  {
    serialNo: 4,
    roomName: 'Lab Room 3',
    availability: '✅',
    description: 'Chemistry experiments',
    reservedDate: '2024-03-15',
    reservedHours: 2,
  },
  {
    serialNo: 5,
    roomName: 'Auditorium B',
    availability: '✅',
    description: 'Guest Speaker Event',
    reservedDate: '2024-03-20',
    reservedHours: 5,
  },
  {
    serialNo: 6,
    roomName: 'Conference Room',
    availability: '🔴',
    description: 'Board Meeting',
    reservedDate: '2024-03-22',
    reservedHours: 3,
  },
  {
    serialNo: 7,
    roomName: 'Computer Lab',
    availability: '✅',
    description: 'Programming workshop',
    reservedDate: '2024-03-25',
    reservedHours: 6,
  },
  {
    serialNo: 8,
    roomName: 'Music Room',
    availability: '✅',
    description: 'Practice Session',
    reservedDate: '2024-03-28',
    reservedHours: 4,
  },
  {
    serialNo: 9,
    roomName: 'Art Studio',
    availability: '✅',
    description: 'Painting class',
    reservedDate: '2024-03-29',
    reservedHours: 2,
  },
  {
    serialNo: 10,
    roomName: 'Library',
    availability: '✅',
    description: 'Quiet study area',
    reservedDate: '2024-03-30',
    reservedHours: 8,
  },
];
