export const Students = [
  {
    id: '1',
    serialNo: 1,
    firstName: 'Alice',
    lastName: 'Smith',
    classSection: {
      classname: 'Math',
      classsectionid: 1,
    },
    age: 16,
    gender: 'Female',
    contactNo: '+1 555 1234 5678',
    Address: {
      city: 'New York',
      state: 'New York',
      country: 'USA',
      zipcode: '10001',
    },
    avatar: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250',
  },
  {
    id: '2',
    serialNo: 2,
    firstName: 'Bob',
    lastName: 'Johnson',
    classSection: {
      classname: 'Science',
      classsectionid: 2,
    },
    age: 15,
    gender: 'Male',
    contactNo: '+1 555 9876 5432',
    Address: {
      city: 'Los Angeles',
      state: 'California',
      country: 'USA',
      zipcode: '90001',
    },
    avatar: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250',
  },
  {
    id: '3',
    serialNo: 3,
    firstName: 'Charlie',
    lastName: 'Brown',
    classSection: {
      classname: 'History',
      classsectionid: 3,
    },
    age: 17,
    gender: 'Male',
    contactNo: '+1 555 2468 1357',
    Address: {
      city: 'Chicago',
      state: 'Illinois',
      country: 'USA',
      zipcode: '60601',
    },
    avatar: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250',
  },
  {
    id: '4',
    serialNo: 4,
    firstName: 'David',
    lastName: 'Lee',
    classSection: {
      classname: 'English',
      classsectionid: 1,
    },
    age: 14,
    gender: 'Male',
    contactNo: '+1 555 3698 7412',
    Address: {
      city: 'Houston',
      state: 'Texas',
      country: 'USA',
      zipcode: '77001',
    },
    avatar: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250',
  },
  {
    id: '5',
    serialNo: 5,
    firstName: 'Emma',
    lastName: 'Taylor',
    classSection: {
      classname: 'Art',
      classsectionid: 2,
    },
    age: 16,
    gender: 'Female',
    contactNo: '+1 555 7531 9846',
    Address: {
      city: 'Phoenix',
      state: 'Arizona',
      country: 'USA',
      zipcode: '85001',
    },
    avatar: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250',
  },
  {
    id: '6',
    serialNo: 6,
    firstName: 'Frank',
    lastName: 'Wilson',
    classSection: {
      classname: 'Music',
      classsectionid: 3,
    },
    age: 15,
    gender: 'Male',
    contactNo: '+1 555 8642 9753',
    Address: {
      city: 'Philadelphia',
      state: 'Pennsylvania',
      country: 'USA',
      zipcode: '19101',
    },
    avatar: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250',
  },
  {
    id: '7',
    serialNo: 7,
    firstName: 'Grace',
    lastName: 'Martinez',
    classSection: {
      classname: 'PE',
      classsectionid: 1,
    },
    age: 17,
    gender: 'Female',
    contactNo: '+1 555 2587 9631',
    Address: {
      city: 'San Antonio',
      state: 'Texas',
      country: 'USA',
      zipcode: '78201',
    },
    avatar: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250',
  },
  {
    id: '8',
    serialNo: 8,
    firstName: 'Henry',
    lastName: 'Garcia',
    classSection: {
      classname: 'Math',
      classsectionid: 2,
    },
    age: 14,
    gender: 'Male',
    contactNo: '+1 555 4567 8901',
    Address: {
      city: 'San Diego',
      state: 'California',
      country: 'USA',
      zipcode: '92101',
    },
    avatar: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250',
  },
  {
    id: '9',
    serialNo: 9,
    firstName: 'Ivy',
    lastName: 'Lopez',
    classSection: {
      classname: 'Science',
      classsectionid: 3,
    },
    age: 16,
    gender: 'Female',
    contactNo: '+1 555 1357 2468',
    Address: {
      city: 'Dallas',
      state: 'Texas',
      country: 'USA',
      zipcode: '75201',
    },
    avatar: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250',
  },
  {
    id: '10',
    serialNo: 10,
    firstName: 'Jack',
    lastName: 'Young',
    classSection: {
      classname: 'History',
      classsectionid: 1,
    },
    age: 15,
    gender: 'Male',
    contactNo: '+1 555 9876 5432',
    Address: {
      city: 'San Jose',
      state: 'California',
      country: 'USA',
      zipcode: '95101',
    },
    avatar: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250',
  },
  {
    id: '11',
    serialNo: 11,
    firstName: 'Katie',
    lastName: 'Miller',
    classSection: {
      classname: 'English',
      classsectionid: 2,
    },
    age: 17,
    gender: 'Female',
    contactNo: '+1 555 3698 7412',
    Address: {
      city: 'New York',
      state: 'New York',
      country: 'USA',
      zipcode: '10001',
    },
    avatar: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250',
  },
  {
    id: '12',
    serialNo: 12,
    firstName: 'Liam',
    lastName: 'Brown',
    classSection: {
      classname: 'Art',
      classsectionid: 3,
    },
    age: 14,
    gender: 'Male',
    contactNo: '+1 555 7531 9846',
    Address: {
      city: 'Los Angeles',
      state: 'California',
      country: 'USA',
      zipcode: '90001',
    },
    avatar: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250',
  },
  {
    id: '13',
    serialNo: 13,
    firstName: 'Mia',
    lastName: 'Jones',
    classSection: {
      classname: 'Music',
      classsectionid: 1,
    },
    age: 16,
    gender: 'Female',
    contactNo: '+1 555 8642 9753',
    Address: {
      city: 'Chicago',
      state: 'Illinois',
      country: 'USA',
      zipcode: '60601',
    },
    avatar: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250',
  },
  {
    id: '14',
    serialNo: 14,
    firstName: 'Noah',
    lastName: 'Martinez',
    classSection: {
      classname: 'PE',
      classsectionid: 2,
    },
    age: 15,
    gender: 'Male',
    contactNo: '+1 555 2587 9631',
    Address: {
      city: 'Houston',
      state: 'Texas',
      country: 'USA',
      zipcode: '77001',
    },
    avatar: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250',
  },
  {
    id: '15',
    serialNo: 15,
    firstName: 'Olivia',
    lastName: 'Rodriguez',
    classSection: {
      classname: 'Math',
      classsectionid: 3,
    },
    age: 17,
    gender: 'Female',
    contactNo: '+1 555 4567 8901',
    Address: {
      city: 'Phoenix',
      state: 'Arizona',
      country: 'USA',
      zipcode: '85001',
    },
    avatar: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250',
  },
  {
    id: '16',
    serialNo: 16,
    firstName: 'Peter',
    lastName: 'Hernandez',
    classSection: {
      classname: 'Science',
      classsectionid: 1,
    },
    age: 14,
    gender: 'Male',
    contactNo: '+1 555 1357 2468',
    Address: {
      city: 'Philadelphia',
      state: 'Pennsylvania',
      country: 'USA',
      zipcode: '19101',
    },
    avatar: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250',
  },
  {
    id: '17',
    serialNo: 17,
    firstName: 'Quinn',
    lastName: 'Gonzalez',
    classSection: {
      classname: 'History',
      classsectionid: 2,
    },
    age: 16,
    gender: 'Female',
    contactNo: '+1 555 9876 5432',
    Address: {
      city: 'San Antonio',
      state: 'Texas',
      country: 'USA',
      zipcode: '78201',
    },
    avatar: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250',
  },
  {
    id: '18',
    serialNo: 18,
    firstName: 'Rachel',
    lastName: 'Perez',
    classSection: {
      classname: 'English',
      classsectionid: 3,
    },
    age: 15,
    gender: 'Female',
    contactNo: '+1 555 3698 7412',
    Address: {
      city: 'San Diego',
      state: 'California',
      country: 'USA',
      zipcode: '92101',
    },
    avatar: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250',
  },
  {
    id: '19',
    serialNo: 19,
    firstName: 'Sam',
    lastName: 'Young',
    classSection: {
      classname: 'Art',
      classsectionid: 1,
    },
    age: 17,
    gender: 'Male',
    contactNo: '+1 555 7531 9846',
    Address: {
      city: 'Dallas',
      state: 'Texas',
      country: 'USA',
      zipcode: '75201',
    },
    avatar: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250',
  },
  {
    id: '20',
    serialNo: 20,
    firstName: 'Taylor',
    lastName: 'Walker',
    classSection: {
      classname: 'Music',
      classsectionid: 2,
    },
    age: 14,
    gender: 'Female',
    contactNo: '+1 555 8642 9753',
    Address: {
      city: 'San Jose',
      state: 'California',
      country: 'USA',
      zipcode: '95101',
    },
    avatar: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250',
  },
];
