export const Teachers = [
  {
    id: '1',
    serialNo: 1,
    firstName: 'John',
    lastName: 'Doe',
    subjects: [
      { subjectName: 'Math', subjectid: 1 },
      { subjectName: 'Physics', subjectid: 2 },
    ],
    age: 35,
    gender: 'Male',
    contactNo: '+1 555 1234 5678',
    Address: {
      city: 'New York',
      state: 'New York',
      country: 'USA',
      zipcode: '10001',
    },
    avatar:
      'https://media.istockphoto.com/id/1201886412/photo/portrait-of-an-african-american-young-woman-in-sunglasses-isolated-on-a-black-background-in.jpg?s=2048x2048&w=is&k=20&c=fx__X7iGv1bRVl-1vBZI26gzsYCtk28yYtX8v7VQe1g=',
  },
  {
    id: '2',
    serialNo: 2,
    firstName: 'Jane',
    lastName: 'Smith',
    subjects: [
      { subjectName: 'History', subjectid: 3 },
      { subjectName: 'Literature', subjectid: 4 },
    ],
    age: 40,
    gender: 'Female',
    contactNo: '+1 555 9876 5432',
    Address: {
      city: 'Los Angeles',
      state: 'California',
      country: 'USA',
      zipcode: '90001',
    },
    avatar:
      'https://media.istockphoto.com/id/1201886412/photo/portrait-of-an-african-american-young-woman-in-sunglasses-isolated-on-a-black-background-in.jpg?s=2048x2048&w=is&k=20&c=fx__X7iGv1bRVl-1vBZI26gzsYCtk28yYtX8v7VQe1g=',
  },
  {
    id: '3',
    serialNo: 3,
    firstName: 'David',
    lastName: 'Johnson',
    subjects: [
      { subjectName: 'Biology', subjectid: 5 },
      { subjectName: 'Chemistry', subjectid: 6 },
    ],
    age: 38,
    gender: 'Male',
    contactNo: '+1 555 2468 1357',
    Address: {
      city: 'Chicago',
      state: 'Illinois',
      country: 'USA',
      zipcode: '60601',
    },
    avatar:
      'https://media.istockphoto.com/id/1201886412/photo/portrait-of-an-african-american-young-woman-in-sunglasses-isolated-on-a-black-background-in.jpg?s=2048x2048&w=is&k=20&c=fx__X7iGv1bRVl-1vBZI26gzsYCtk28yYtX8v7VQe1g=',
  },
  {
    id: '4',
    serialNo: 4,
    firstName: 'Emily',
    lastName: 'Williams',
    subjects: [
      { subjectName: 'English', subjectid: 7 },
      { subjectName: 'French', subjectid: 8 },
    ],
    age: 45,
    gender: 'Female',
    contactNo: '+1 555 3698 7412',
    Address: {
      city: 'Houston',
      state: 'Texas',
      country: 'USA',
      zipcode: '77001',
    },
    avatar:
      'https://media.istockphoto.com/id/1201886412/photo/portrait-of-an-african-american-young-woman-in-sunglasses-isolated-on-a-black-background-in.jpg?s=2048x2048&w=is&k=20&c=fx__X7iGv1bRVl-1vBZI26gzsYCtk28yYtX8v7VQe1g=',
  },
  {
    id: '5',
    serialNo: 5,
    firstName: 'Michael',
    lastName: 'Brown',
    subjects: [
      { subjectName: 'Geography', subjectid: 9 },
      { subjectName: 'Social Studies', subjectid: 10 },
    ],
    age: 42,
    gender: 'Male',
    contactNo: '+1 555 1357 2468',
    Address: {
      city: 'Philadelphia',
      state: 'Pennsylvania',
      country: 'USA',
      zipcode: '19101',
    },
    avatar:
      'https://media.istockphoto.com/id/1201886412/photo/portrait-of-an-african-american-young-woman-in-sunglasses-isolated-on-a-black-background-in.jpg?s=2048x2048&w=is&k=20&c=fx__X7iGv1bRVl-1vBZI26gzsYCtk28yYtX8v7VQe1g=',
  },
  {
    id: '6',
    serialNo: 6,
    firstName: 'Sarah',
    lastName: 'Garcia',
    subjects: [
      { subjectName: 'Computer Science', subjectid: 11 },
      { subjectName: 'Programming', subjectid: 12 },
    ],
    age: 37,
    gender: 'Female',
    contactNo: '+1 555 8642 9753',
    Address: {
      city: 'San Antonio',
      state: 'Texas',
      country: 'USA',
      zipcode: '78201',
    },
    avatar:
      'https://media.istockphoto.com/id/1201886412/photo/portrait-of-an-african-american-young-woman-in-sunglasses-isolated-on-a-black-background-in.jpg?s=2048x2048&w=is&k=20&c=fx__X7iGv1bRVl-1vBZI26gzsYCtk28yYtX8v7VQe1g=',
  },
  {
    id: '7',
    serialNo: 7,
    firstName: 'James',
    lastName: 'Martinez',
    subjects: [
      { subjectName: 'Economics', subjectid: 13 },
      { subjectName: 'Business Studies', subjectid: 14 },
    ],
    age: 39,
    gender: 'Male',
    contactNo: '+1 555 2587 9631',
    Address: {
      city: 'San Diego',
      state: 'California',
      country: 'USA',
      zipcode: '92101',
    },
    avatar:
      'https://media.istockphoto.com/id/1201886412/photo/portrait-of-an-african-american-young-woman-in-sunglasses-isolated-on-a-black-background-in.jpg?s=2048x2048&w=is&k=20&c=fx__X7iGv1bRVl-1vBZI26gzsYCtk28yYtX8v7VQe1g=',
  },
  {
    id: '8',
    serialNo: 8,
    firstName: 'Sophia',
    lastName: 'Lopez',
    subjects: [
      { subjectName: 'Art', subjectid: 15 },
      { subjectName: 'Music', subjectid: 16 },
    ],
    age: 41,
    gender: 'Female',
    contactNo: '+1 555 7531 9846',
    Address: {
      city: 'Phoenix',
      state: 'Arizona',
      country: 'USA',
      zipcode: '85001',
    },
    avatar:
      'https://media.istockphoto.com/id/1201886412/photo/portrait-of-an-african-american-young-woman-in-sunglasses-isolated-on-a-black-background-in.jpg?s=2048x2048&w=is&k=20&c=fx__X7iGv1bRVl-1vBZI26gzsYCtk28yYtX8v7VQe1g=',
  },
  {
    id: '9',
    serialNo: 9,
    firstName: 'William',
    lastName: 'Hernandez',
    subjects: [
      { subjectName: 'Physical Education', subjectid: 17 },
      { subjectName: 'Health', subjectid: 18 },
    ],
    age: 36,
    gender: 'Male',
    contactNo: '+1 555 9823 6471',
    Address: {
      city: 'San Jose',
      state: 'California',
      country: 'USA',
      zipcode: '95101',
    },
    avatar:
      'https://media.istockphoto.com/id/1201886412/photo/portrait-of-an-african-american-young-woman-in-sunglasses-isolated-on-a-black-background-in.jpg?s=2048x2048&w=is&k=20&c=fx__X7iGv1bRVl-1vBZI26gzsYCtk28yYtX8v7VQe1g=',
  },
  {
    id: '10',
    serialNo: 10,
    firstName: 'Olivia',
    lastName: 'Gonzalez',
    subjects: [
      { subjectName: 'Drama', subjectid: 19 },
      { subjectName: 'Film Studies', subjectid: 20 },
    ],
    age: 43,
    gender: 'Female',
    contactNo: '+1 555 7398 1246',
    Address: {
      city: 'Dallas',
      state: 'Texas',
      country: 'USA',
      zipcode: '75201',
    },
    avatar:
      'https://media.istockphoto.com/id/1201886412/photo/portrait-of-an-african-american-young-woman-in-sunglasses-isolated-on-a-black-background-in.jpg?s=2048x2048&w=is&k=20&c=fx__X7iGv1bRVl-1vBZI26gzsYCtk28yYtX8v7VQe1g=',
  },
  {
    id: '11',
    serialNo: 11,
    firstName: 'Daniel',
    lastName: 'Rodriguez',
    subjects: [
      { subjectName: 'Chemistry', subjectid: 21 },
      { subjectName: 'Biology', subjectid: 22 },
    ],
    age: 39,
    gender: 'Male',
    contactNo: '+1 555 8642 3579',
    Address: {
      city: 'Miami',
      state: 'Florida',
      country: 'USA',
      zipcode: '33101',
    },
    avatar:
      'https://media.istockphoto.com/id/1201886412/photo/portrait-of-an-african-american-young-woman-in-sunglasses-isolated-on-a-black-background-in.jpg?s=2048x2048&w=is&k=20&c=fx__X7iGv1bRVl-1vBZI26gzsYCtk28yYtX8v7VQe1g=',
  },
  {
    id: '12',
    serialNo: 12,
    firstName: 'Ava',
    lastName: 'Perez',
    subjects: [
      { subjectName: 'Geology', subjectid: 23 },
      { subjectName: 'Astronomy', subjectid: 24 },
    ],
    age: 37,
    gender: 'Female',
    contactNo: '+1 555 9213 4865',
    Address: {
      city: 'Seattle',
      state: 'Washington',
      country: 'USA',
      zipcode: '98101',
    },
    avatar:
      'https://media.istockphoto.com/id/1201886412/photo/portrait-of-an-african-american-young-woman-in-sunglasses-isolated-on-a-black-background-in.jpg?s=2048x2048&w=is&k=20&c=fx__X7iGv1bRVl-1vBZI26gzsYCtk28yYtX8v7VQe1g=',
  },
  {
    id: '13',
    serialNo: 13,
    firstName: 'Ethan',
    lastName: 'Taylor',
    subjects: [
      { subjectName: 'Psychology', subjectid: 25 },
      { subjectName: 'Sociology', subjectid: 26 },
    ],
    age: 41,
    gender: 'Male',
    contactNo: '+1 555 4862 3579',
    Address: {
      city: 'Boston',
      state: 'Massachusetts',
      country: 'USA',
      zipcode: '02101',
    },
    avatar:
      'https://media.istockphoto.com/id/1201886412/photo/portrait-of-an-african-american-young-woman-in-sunglasses-isolated-on-a-black-background-in.jpg?s=2048x2048&w=is&k=20&c=fx__X7iGv1bRVl-1vBZI26gzsYCtk28yYtX8v7VQe1g=',
  },
  {
    id: '14',
    serialNo: 14,
    firstName: 'Mia',
    lastName: 'Gonzalez',
    subjects: [
      { subjectName: 'Physical Science', subjectid: 27 },
      { subjectName: 'Environmental Science', subjectid: 28 },
    ],
    age: 38,
    gender: 'Female',
    contactNo: '+1 555 7392 4861',
    Address: {
      city: 'Atlanta',
      state: 'Georgia',
      country: 'USA',
      zipcode: '30301',
    },
    avatar:
      'https://media.istockphoto.com/id/1201886412/photo/portrait-of-an-african-american-young-woman-in-sunglasses-isolated-on-a-black-background-in.jpg?s=2048x2048&w=is&k=20&c=fx__X7iGv1bRVl-1vBZI26gzsYCtk28yYtX8v7VQe1g=',
  },
  {
    id: '15',
    serialNo: 15,
    firstName: 'Jacob',
    lastName: 'Lopez',
    subjects: [
      { subjectName: 'Political Science', subjectid: 29 },
      { subjectName: 'Government', subjectid: 30 },
    ],
    age: 40,
    gender: 'Male',
    contactNo: '+1 555 9214 4862',
    Address: {
      city: 'Washington',
      state: 'D.C.',
      country: 'USA',
      zipcode: '20001',
    },
    avatar:
      'https://media.istockphoto.com/id/1201886412/photo/portrait-of-an-african-american-young-woman-in-sunglasses-isolated-on-a-black-background-in.jpg?s=2048x2048&w=is&k=20&c=fx__X7iGv1bRVl-1vBZI26gzsYCtk28yYtX8v7VQe1g=',
  },
  {
    id: '16',
    serialNo: 16,
    firstName: 'Isabella',
    lastName: 'Martinez',
    subjects: [
      { subjectName: 'Anthropology', subjectid: 31 },
      { subjectName: 'Archaeology', subjectid: 32 },
    ],
    age: 36,
    gender: 'Female',
    contactNo: '+1 555 7392 4863',
    Address: {
      city: 'Denver',
      state: 'Colorado',
      country: 'USA',
      zipcode: '80201',
    },
    avatar:
      'https://media.istockphoto.com/id/1201886412/photo/portrait-of-an-african-american-young-woman-in-sunglasses-isolated-on-a-black-background-in.jpg?s=2048x2048&w=is&k=20&c=fx__X7iGv1bRVl-1vBZI26gzsYCtk28yYtX8v7VQe1g=',
  },
  {
    id: '17',
    serialNo: 17,
    firstName: 'Alexander',
    lastName: 'Gomez',
    subjects: [
      { subjectName: 'Philosophy', subjectid: 33 },
      { subjectName: 'Ethics', subjectid: 34 },
    ],
    age: 42,
    gender: 'Male',
    contactNo: '+1 555 8642 3579',
    Address: {
      city: 'Portland',
      state: 'Oregon',
      country: 'USA',
      zipcode: '97201',
    },
    avatar:
      'https://media.istockphoto.com/id/1201886412/photo/portrait-of-an-african-american-young-woman-in-sunglasses-isolated-on-a-black-background-in.jpg?s=2048x2048&w=is&k=20&c=fx__X7iGv1bRVl-1vBZI26gzsYCtk28yYtX8v7VQe1g=',
  },
  {
    id: '18',
    serialNo: 18,
    firstName: 'Charlotte',
    lastName: 'Hernandez',
    subjects: [
      { subjectName: 'Criminal Justice', subjectid: 35 },
      { subjectName: 'Law', subjectid: 36 },
    ],
    age: 38,
    gender: 'Female',
    contactNo: '+1 555 9213 4861',
    Address: {
      city: 'Las Vegas',
      state: 'Nevada',
      country: 'USA',
      zipcode: '89101',
    },
    avatar:
      'https://media.istockphoto.com/id/1201886412/photo/portrait-of-an-african-american-young-woman-in-sunglasses-isolated-on-a-black-background-in.jpg?s=2048x2048&w=is&k=20&c=fx__X7iGv1bRVl-1vBZI26gzsYCtk28yYtX8v7VQe1g=',
  },
  {
    id: '19',
    serialNo: 19,
    firstName: 'Benjamin',
    lastName: 'Rodriguez',
    subjects: [
      { subjectName: 'Statistics', subjectid: 37 },
      { subjectName: 'Data Science', subjectid: 38 },
    ],
    age: 39,
    gender: 'Male',
    contactNo: '+1 555 4862 3579',
    Address: {
      city: 'San Francisco',
      state: 'California',
      country: 'USA',
      zipcode: '94101',
    },
    avatar:
      'https://media.istockphoto.com/id/1201886412/photo/portrait-of-an-african-american-young-woman-in-sunglasses-isolated-on-a-black-background-in.jpg?s=2048x2048&w=is&k=20&c=fx__X7iGv1bRVl-1vBZI26gzsYCtk28yYtX8v7VQe1g=',
  },
  {
    id: '20',
    serialNo: 20,
    firstName: 'Amelia',
    lastName: 'Gomez',
    subjects: [
      { subjectName: 'Nutrition', subjectid: 39 },
      { subjectName: 'Dietetics', subjectid: 40 },
    ],
    age: 37,
    gender: 'Female',
    contactNo: '+1 555 7392 4861',
    Address: {
      city: 'Miami',
      state: 'Florida',
      country: 'USA',
      zipcode: '33101',
    },
    avatar:
      'https://media.istockphoto.com/id/1201886412/photo/portrait-of-an-african-american-young-woman-in-sunglasses-isolated-on-a-black-background-in.jpg?s=2048x2048&w=is&k=20&c=fx__X7iGv1bRVl-1vBZI26gzsYCtk28yYtX8v7VQe1g=',
  },
];
